export const elements = {
    toolbar: document.querySelector('.toolbar'),
    logo: document.querySelector('.js--logo'),
    hideWrapper: document.querySelector('.js--hide-wrapper'),
    loader: document.querySelector('.js--loader'),
    formLoader: document.querySelector('.js--form-loader'),
    mobileNav: document.querySelector('.js--mobile-nav'),
    menuIcon: document.querySelector('.js--menu'),
    menuIconClose: document.querySelector('.js--menu-close'),
    menuIconCloseSmall: document.querySelector('.js--menu-close-small'),
    modal: document.querySelector('.js--modal'),
    mobileNavLinks: document.querySelectorAll('.js--mobile-link'),
    // Contact Form
    contactForm: document.querySelector('.js--form'),
    sendMsg: document.querySelector('.js--send-msg'),
    formSend: document.querySelector('.js--form-send'),
    btnModalClose: document.querySelector('.js--button-close-modal'),
    morePeople: document.querySelector('.js--other-people'),
    addPersonBtn: document.querySelector('.js--add-person'),
    removePersonBtn: document.querySelector('.js--remove-person'),
    checkAll: document.querySelector('.js--check-all'),
    allChecks: document.querySelectorAll('.js--check'),

    adminDash: document.querySelector('.js--admin'),
}